version: '3'

services:     ## Determina os containeres que serão executados
  web:        ## Nome dado para o container q está neste projeto
    build: .  ## Builda o container a partir da própria pasta onde estamos. Com os parâmetros do nosso Dockerfile. Poderia ser qualquer imagem já pronta no Docker Hub
    command: python manage.py runserver 0.0.0.0:8000    ## Comando que será executado para rodar o servidor 
    ports:
      - "8000:8000"    ## Tanto o container quanto a máquina local estarão na mesma porta