# Generated by Django 5.0.7 on 2024-08-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='date_response',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
