# Generated by Django 5.0.7 on 2024-08-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_alter_report_responsible'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='observations',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
