# Generated by Django 5.0.7 on 2024-08-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_report_observations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='validation_report',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
